################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.c \
D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.c \
D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.c \
D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.c \
D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.c \
D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.c 

C_DEPS += \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.d \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.d \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.d \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.d \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.d \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.d 

OBJS += \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.o \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.o \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.o \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.o \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.o \
./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.o 


# Each subdirectory must supply rules for building sources it contributes
CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.o: D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.c CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../STM32_WPAN/App -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Utilities/lpm/tiny_lpm -I../Middlewares/ST/STM32_WPAN -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../Middlewares/ST/STM32_WPAN/utilities -I../Middlewares/ST/STM32_WPAN/ble/core -I../Middlewares/ST/STM32_WPAN/ble/core/auto -I../Middlewares/ST/STM32_WPAN/ble/core/template -I../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Utilities/sequencer -I../Middlewares/ST/STM32_WPAN/ble -I../Drivers/CMSIS/Include -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM" -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686" -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.o: D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.c CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../STM32_WPAN/App -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Utilities/lpm/tiny_lpm -I../Middlewares/ST/STM32_WPAN -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../Middlewares/ST/STM32_WPAN/utilities -I../Middlewares/ST/STM32_WPAN/ble/core -I../Middlewares/ST/STM32_WPAN/ble/core/auto -I../Middlewares/ST/STM32_WPAN/ble/core/template -I../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Utilities/sequencer -I../Middlewares/ST/STM32_WPAN/ble -I../Drivers/CMSIS/Include -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM" -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686" -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.o: D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.c CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../STM32_WPAN/App -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Utilities/lpm/tiny_lpm -I../Middlewares/ST/STM32_WPAN -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../Middlewares/ST/STM32_WPAN/utilities -I../Middlewares/ST/STM32_WPAN/ble/core -I../Middlewares/ST/STM32_WPAN/ble/core/auto -I../Middlewares/ST/STM32_WPAN/ble/core/template -I../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Utilities/sequencer -I../Middlewares/ST/STM32_WPAN/ble -I../Drivers/CMSIS/Include -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM" -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686" -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.o: D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.c CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../STM32_WPAN/App -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Utilities/lpm/tiny_lpm -I../Middlewares/ST/STM32_WPAN -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../Middlewares/ST/STM32_WPAN/utilities -I../Middlewares/ST/STM32_WPAN/ble/core -I../Middlewares/ST/STM32_WPAN/ble/core/auto -I../Middlewares/ST/STM32_WPAN/ble/core/template -I../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Utilities/sequencer -I../Middlewares/ST/STM32_WPAN/ble -I../Drivers/CMSIS/Include -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM" -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686" -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.o: D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.c CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../STM32_WPAN/App -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Utilities/lpm/tiny_lpm -I../Middlewares/ST/STM32_WPAN -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../Middlewares/ST/STM32_WPAN/utilities -I../Middlewares/ST/STM32_WPAN/ble/core -I../Middlewares/ST/STM32_WPAN/ble/core/auto -I../Middlewares/ST/STM32_WPAN/ble/core/template -I../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Utilities/sequencer -I../Middlewares/ST/STM32_WPAN/ble -I../Drivers/CMSIS/Include -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM" -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686" -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.o: D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.c CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -DUSE_HAL_DRIVER -DSTM32WB55xx -c -I../Core/Inc -I../STM32_WPAN/App -I../Drivers/STM32WBxx_HAL_Driver/Inc -I../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../Utilities/lpm/tiny_lpm -I../Middlewares/ST/STM32_WPAN -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../Middlewares/ST/STM32_WPAN/utilities -I../Middlewares/ST/STM32_WPAN/ble/core -I../Middlewares/ST/STM32_WPAN/ble/core/auto -I../Middlewares/ST/STM32_WPAN/ble/core/template -I../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../Utilities/sequencer -I../Middlewares/ST/STM32_WPAN/ble -I../Drivers/CMSIS/Include -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM" -I"D:/Projects/Vantare_VantageSuit/Firmware/LIBRARY/CUSTOM/motion.mcu.icm45686.driver/icm45686" -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-CUSTOM-2f-motion-2e-mcu-2e-icm45686-2e-driver-2f-icm45686-2f-imu

clean-CUSTOM-2f-motion-2e-mcu-2e-icm45686-2e-driver-2f-icm45686-2f-imu:
	-$(RM) ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.cyclo ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.d ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.o ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver.su ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.cyclo ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.d ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.o ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_advanced.su ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.cyclo ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.d ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.o ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_driver_aux1.su ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.cyclo ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.d ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.o ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_edmp.su ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.cyclo ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.d ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.o ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_selftest.su ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.cyclo ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.d ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.o ./CUSTOM/motion.mcu.icm45686.driver/icm45686/imu/inv_imu_transport.su

.PHONY: clean-CUSTOM-2f-motion-2e-mcu-2e-icm45686-2e-driver-2f-icm45686-2f-imu

